plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://understanding-machine.github.io
baseurl: /depsekrp

title: Understanding Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Understanding-Machine
  verb: Understanding
  instructions_file: understanding.md
  token: depsek
  server: https://localhost:443
  apiUrl: https://api.deepseek.com/chat/completions

app:
  worker_name: depsekapi.js

lm:
  model: deepseek-reasoner
  max_tokens: 65536

github_settings:
  owner: understanding-machine
  repo: understanding_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
